---
title: "Replace with Main Title"
author: "Your Name"
date: "AUTOMATIC"
---


```{r echo=FALSE, message=FALSE}
# include this code chunk as-is to set options
knitr::opts_chunk$set(comment=NA, prompt=TRUE)
library(Rcmdr)
library(car)
library(RcmdrMisc)
```


```{r echo=FALSE}
# include this code chunk as-is to enable 3D graphs
library(rgl)
knitr::knit_hooks$set(webgl = hook_webgl)
```


```{r}
# A simple and non-exhaustive analysis for the price of the houses in the Boston
```


```{r}
# dataset. The purpose is to quantify, by means of a multiple linear model,
```


```{r}
# the effect of 14 variables in the price of a house in the suburbs of Boston.
```


```{r}
# Import data
```


```{r}
library(MASS)
```


```{r}
data(Boston)
```


```{r}
# Make a multiple linear regression od medv in the rest of variables
```


```{r}
mod <- lm(medv ~ ., data = Boston)
```


```{r}
summary(mod)
```


```{r}
# Check the linearty assumption
```


```{r}
plot(mod, 1) # Clear non-linearity
```


```{r}
# Let's consider the transformations given in Harrison and Rubinfeld (1978)
```


```{r}
modTransf <- lm(I(log(medv * 1000)) ~ I(rm^2) + age + log(dis) +
                  log(rad) + tax + ptratio + I(black / 1000) +
                  I(log(lstat / 100)) + crim + zn + indus + chas +
                  I((10 * nox)^2), data = Boston)
```


```{r}
summary(modTransf)
```


```{r}
# The non-linearity is more subtle now
```


```{r}
plot(modTransf, 1)
```


```{r}
# Look for the best model in terms of the BIC
```


```{r}
modTransfBIC <- stepwise(modTransf, trace = 0)
```


```{r}
summary(modTransfBIC)
```


```{r}
# Let's explore the most significant variables, to see if the model can be
```


```{r}
# reduced drastically in complexity
```


```{r}
mod3D <- lm(I(log(medv * 1000)) ~ I(log(lstat / 100)) + crim, data = Boston)
```


```{r}
summary(mod3D)
```


```{r}
# With only 2 variables, we explain the 72% of variability.
```


```{r}
# Compared with the 80% with 10 variables, it is an important improvement
```


```{r}
# in terms of simplicity.
```


```{r}
# Let's add these variables to the dataset, so we can call scatterplotMatrix
```


```{r}
# and scatter3d through R Commander's menu
```


```{r}
Boston$logMedv <- log(Boston$medv * 1000)
```


```{r}
Boston$logLstat <- log(Boston$lstat / 100)
```


```{r}
# Visualize the pair-by-pair relations of the response and two predictors
```


```{r}
scatterplotMatrix(~ crim + logLstat + logMedv, reg.line = lm, smooth = FALSE,
                  spread = FALSE, span = 0.5, ellipse = FALSE,
                  levels = c(.5, .9), id.n = 0, diagonal = 'histogram',
                  data = Boston)
```


```{r}
# Visualize the full relation between the response and the two predictors
```


```{r webgl=TRUE}
scatter3d(logMedv ~ crim + logLstat, data = Boston, fit = "linear",
          residuals = TRUE, bg = "white", axis.scales = TRUE, grid = TRUE,
          ellipsoid = FALSE)
```


