---
output: html_document
author: Eduardo García-Portugués
runtime: shiny
---

```{r, echo = FALSE}
set.seed(34567)
x <- rnorm(50)
eps <- rnorm(50, sd = 0.5)
yLin <- -0.5 + 1.5 * x + eps
yQua <- -0.5 + 1.5 * x^2 + eps
yExp <- -0.5 + 1.5 * 2^x + eps
red <- rgb(1, 0, 0, alpha = 0.75)
```

```{r, echo = FALSE}

# Define input
inputPanel(
  
  selectInput(inputId = "dataType", label = "Data pattern:", choices = c("linear", "quadratic", "exponential")),
  selectInput(inputId = "distType", label = "Type of distance:", choices = c("vertical", "horizontal", "perpendicular")),
  sliderInput(inputId = "beta0", label = "Intercept:",
              min = -3, max = 3, value = 0, step = 0.05),
  sliderInput(inputId = "beta1", label = "Slope:",
              min = -3, max = 3, value = 0, step = 0.05)
  
)

# Create plot
renderPlot({
  
  # Response  
  y <- switch(input$dataType,
    linear = yLin,
    quadratic = yQua,
    exponential = yExp)
  
  # Plot
  plot(x, y, xlim = c(-5, 5), ylim = c(-5, 5), pch = 16)
  if (input$distType == "vertical") {
    
    # Regression
    yReg <- input$beta0 + input$beta1 * x
    
    segments(x0 = x, y0 = y, x1 = x, y1 = yReg, col = red, lty = 2)
    title(main = paste("Sum of squared distances:", sprintf("%.2f", sum((yReg - y)^2))), cex.main = 1.5)
    
  } else if (input$distType == "horizontal") {
    
    # Regression
    xReg <- (y - input$beta0) / input$beta1
    
    segments(x0 = x, y0 = y, x1 = xReg, y1 = y, col = red, lty = 2)
    title(main = paste("Sum of squared distances:", sprintf("%.2f", sum((xReg - x)^2))), cex.main = 1.5)
    
  } else {
    
    # Projection into a * x + b * y + c = 0
    a <- input$beta1
    b <- -1
    c <- input$beta0
    proj <- cbind(b * (b * x - a * y) - a * c, a * (-b * x + a * y) - b * c) / (a^2 + b^2)
    
    segments(x0 = x, y0 = y, x1 = proj[, 1], y1 = proj[, 2], col = red, lty = 2)
    title(main = paste("Sum of squared distances:", sprintf("%.2f", sum((proj[, 1] - x)^2 + (proj[, 2] - y)^2))), cex.main = 1.5)
    
  }
  abline(a = input$beta0, b = input$beta1, col = 2, lwd = 2)
  
}, width = 650, height = 650)
  
```

